# -*- coding: utf-8 -*-
"""advanced Datatypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQdqAPzDGVRgG7boePCJHJ_0m2L40kQJ
"""

#lists,dictionaries
#tuples

a=1.1
type(a)

a=1,2,3

type(a)

#we cant modify the values of tuple

b=[1,2,3]
type(b)

#tuples are immutable and lists are mutable

b.append(4)

b.remove(4)

a=[1,1.1,'astha',True]
type(a)

a[2]

a

a.insert(2,'python')

a

len(a)

a=1
print(a)
print(id(b))

list1=[1,2,3,4]
list2=list1
list2[2]=0
print(list1)

print(id(list1))
print(id(list2))

list1=[1,2,3,4]
list2=list1.copy()
list2[2]=0
print(list1)

print(id(list1))
print(id(list2))

available_toppings=['onions','olives','cheese']
required_toppings=input("what toppings do you want?")
if required_toppings in available_toppings:
  print("additng "+required_toppings+" finished pizza with "+required_toppings)
else:
  print("sorry "+required_toppings+" not available")

#datasets=rows*columns
#shape of dataframe (dataset)=output will be a tuple

#dictionary
#key,value
d={'name':'astha'}
d

type(d)

d={'name':['astha','aditi','surup','amrit'],'salary':['1000000','2000','30000','4000']}
d

#ML  model-create a dataframe

import pandas as pd
df= pd.DataFrame(d)
df

r = {}

flag = True # Status Checking

while flag:
  name = input('What is your name?') # Key
  workshop = input('Which workshop you want to attend?') # Value

  r[name] = workshop
  repeat = input('Would you like someone else to respond, no for Exit')
  if repeat =='no':
    flag =False

print('Results')

print(r)
# Dictionary  =  r
# Key = Name
# Values = workshop

