# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1in3sNNW5jLNT7LCl7x8VtIOelGIgIi47
"""

import numpy as np
x = np.array([[1],[2],[3],[4],[5],[6]])
y = np.array([10,12,14,16,18,20])
print(x,y)
print(x.ndim)

#another method
x=np.arange(1,7,1)
y=np.arange(10,21,2)
print(x,y)

import matplotlib.pyplot as plt
plt.scatter(x,y)
plt.show()

from sklearn.linear_model import LinearRegression
#from package.family_library(sub_packages) import algorithm
#package -collection of multiple libraries 
#in sklearn, inputs should always be in 2 D 
model = LinearRegression()

model.fit(x,y)
y_pred = model.predict([[2]])

y_pred

model.coef_
#slope 
#y_intercept

model.intercept_

import pandas as pd
df=pd.read_csv('Salary_Data.csv')
df

df.shape

import matplotlib.pyplot as plt
plt.scatter(df['YearsExperience'],df['Salary'])
plt.show()

x = df.iloc[:,[0]].values
y = df.iloc[:,1].values

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)
y_pred = model.predict([[2.5]])
y_pred

model.coef_

model.intercept_

model.coef_*2.5+model.intercept_

plt.scatter(x,y,c = 'r')
plt.plot(x,model.predict(x))
plt.show()

