# -*- coding: utf-8 -*-
"""numpy and matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18G-rcgSHnRR4Y2QLw9gKblN-fJCsvImw
"""

#pre-allocated integers [-5 to 256]

#libraries- set  of codes which consists of lots of functions/methods and attributes/variable
#module-any python proogram 
#all the libraries are module but all module are not libraries 
#package -collection of multiple libraries 
#scikit-learn= 
#there are 2 types of libraries =inbuilt,user defined library 
#numpy/matplotlib,pands,scikit-learn-user defined libraries

#numerical python-scientific computing
#array is a method 
#attributes 
#scalar- no dimensions 
#vector-1 dimensions 
#matrix- 2 dimensions
#np is basically a object

import numpy as np
a=np.array(12)
print(a)

print(a.ndim)  #dimension
print(a.shape)  #the no. of rows and columns etc
print(a.dtype) #datatype
print(a.size) #quantity

#for vector 
b=np.array([1,2,3]) 
print(b)

#attributes
print(b.ndim)  #dimension
print(b.shape)  #the no. of rows and columns etc
print(b.dtype) #datatype
print(b.size) #quantity

#for matrix
c=np.array([[1,2,3],[4,5,6]])
print(c)

#attributes
print(c.ndim)  #dimension
print(c.shape)  #the no. of rows and columns etc(only for matrix)
print(c.dtype) #datatype
print(c.size) #quantity

d= np.array([[[1,2],[2,3],[4,5],
            [2,3],[9,4],[6,7]],
            [[1,2],[2,3],[3,5],
             [2,3],[9,4],[6,7]]])
print(d)

#attributes
print(d.ndim)  #dimension
print(d.shape)  #the no. of rows and columns etc(only for matrix)
print(d.dtype) #datatype
print(d.size) #quantity

e=np.random.randint(0,10,10)
print(e)

e.reshape(2,5)

f=np.random.randint(0,10,size=(3,4))
f

np.zeros([10,10],dtype='uint8')

np.ones([10,10],dtype='uint8')

np.ones(10) #output is related to one

#images-pixels(width*height)
#black images -0
#white image - 255
#here [10,10]- pixels

#matplotlib-data visualisation
#1.line plot(2 points in a condinate geometry)
#2.scatter plot
#3.bar graph
#4.pie char
#seaborn-advanced data visualisation

#line plot
#input:numpy Arrays,lists,tuples
x=[1,2,3]
y=[3,4,4]
z=[7,8,9]
#point A=(1,3)
#point B=(2,4)
import matplotlib.pyplot as plt
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('LINE PLOT')
plt.plot(x,y,c='r',marker='+',label='team 1')
plt.plot(x,z,label='team 2')
plt.legend()
plt.show()

plt.scatter(x,y)

plt.plot(x,y,c='r')
plt.scatter(x,y)
plt.show()

# Bar Graph
name = ['Mr X','Mr Y','Mr Z']
weight = [58,67,45]
height = [120,112,143]
index = np.arange(3)
bar_width = 0.4
plt.bar(index,height ,width = bar_width,color = 'b')
plt.bar(index+0.4,weight ,width = bar_width,color = 'g')
plt.xlabel('Person')
plt.ylabel('Weight')
plt.title('Bar Graph')
plt.show()

#positive for right and negativ for left

x = np.arange(10)
y = np.power(x,2)
plt.plot(x,y)

