# -*- coding: utf-8 -*-
"""P1-Python basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWS9EVREgGGehhcvcoY2NTYs46euLEwF
"""

print("hello world")

1+2

1-2

1*2

1/2

a=1
b=2
a+b
a-b
a*b

a=1
b=2
c=a+b
print(a+b)
print(a-b)
print(a*b)

#datatypes
a=1
b=1.1
c="ameer"
d=True
print(type(a))
print(type(b))
print(type(c))
print(type(d))

#High Level ---->Low Level(compilers/interpreters)
#c,C++,Java-compie
#python-interpreter

print(d)
print(type(d))

#input from the user
name=input()
print(name)

num1=int(input("enter the value of first number"))
num2=int(input("enter the value of second number"))
result=num1+num2
print(result)

num1=int(input("enter the value of first number"))
num2=int(input("enter the value of first number"))
result=num1+num2
print("the sum of {0} and {1} is {2}" .format(num1,num2,result))

print("am"+"e"+"er")

name="astha"
ID= 233
print("my name is "+name+"and my ID is"+str(ID))

print("my name is",name,"and my ID is",ID)

#method 3- format specifiers
print("my name is %s and my ID is %d"%(name,ID))

import sys
sys.version

#method 5-string formatting(version 6 onwards)
print(f"my name is {name} and my ID is {ID}")

#there is no datatype called character in python
name1='a'
name2="astha"
print(type(name1))
print(type(name2))

#single quote-character
#word statement-double quote
#paraghaph-triple quote
'''I m learning python'''

#if and else conditions
age=int(input("enter your age"))
if (age >= 18):
  print("able to vote")
else:
  print("cant't vote,please come after:"+str(18-age)+"years")

number=int(input("enter a number" ))
if number%2==0:
  print("even")
else:
  print("odd")

#while loop
i=0
while(i<=10):
  i+=1
  print(i,end=' ')

print?

#countdown timer
import time
i=10
while(i>=0):
  print(i)
  time.sleep(1)
  i=i-1

#functions
#define a function 
#function call

def add(a,b):
  print(a+b)

add(2,3)

season=input("enter the season")
if (season=='rain'):
  print("it is monsoon")
elif(season=='cold'):
  print("it s winter")
else:
  print("wrong input")

#calculator
#functions-sum,dif,mul,div
#forever loop
#conditions type a  for addition b for subtraction
#break
a=int(input("enter first number"))
b=int(input("enter second number"))
print("\nChoose Options To Perform : ")
print("\nA Addition")
print("\nB Subtraction")
print("\nC Multiplication")
print("\nD Division")
print("\n\nEnter Your Choice :")
choice=input("enter your choice A- addition,B- subtraction C-multiplication D-division Q-")
  if (choice=='A'):
    print(a+b)
  elif (choice=='B'):
    print(a-b)

  elif (choice=='C'):
    print(a*b)
  elif (choice=='D'):
    print(a/d)

  elif (choice=='Q'):
    break
  else:
    print("invalid input")

