# -*- coding: utf-8 -*-
"""statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18wyPQWTegfuTKbKrWt0X5zLleBo0OD6S
"""

#statistics

import numpy as np
a=np.array([4,3,5,2,1,2])

print(np.mean(a))
print(np.sum(a))

print(np.median(a))

#for mode
from scipy import stats
print(int(stats.mode(a)[0]))

np.max(a)

np.min(a)

np.max(a)-np.min(a)

#range
np.ptp(a) #ptp=peak to peak

#variance how far a number  is different from the mean 
np.var(a)

np.std(a,ddof=1) #delta degree of freedoms

np.std?

#pandas - data analysis (refesr to understand one particular data )
#2 objects - 
#1.series - 1 D objects(consisting of columns)
#2.data frame -2 D object (rows *columns)
#datas- numbers, text ,images ,videos,audios
a=np.array([4,3,5,2,1,2])

import pandas as pd
series_demo=pd.Series(a)

series_demo

sports1= pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports2= pd.Series([1,2,5,4],index=['cricket','football','baseball','golf'])

sports1+sports2

sports1= pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports2= pd.Series([1,2,5,4],index=['cricket','football','basketball','golf'])

sports1+sports2

#dataFrame
#list,Tuple,Dictionary
d={'numbers': a,'number 2':[1,2,3,4,5,6]}
print(d)

df=pd.DataFrame(d)
df

type(df)

df['numbers']

df.describe()
#simple statistics in one go

x1=np.percentile(a,25)
x2=np.percentile(a,50)
x3=np.percentile(a,75)
print(x1,x2,x3)

